### ISSUE TITLE
Requires admin account to be used

### ISSUE THREAD

**Issue by sparks1372** [Noltari/aioairzone-cloud#7]
It appears as though you can only users with the Admin user type otherwise you start getting errors. This is a bit suboptimal from a security perspective. With a Basic user type there is the error reported in https://github.com/home-assistant/core/issues/120873 and if you change to an Advanced user type you get a 403 forbidden error upon initialisation, however if you change the account type from Admin to Advanced after the initialisation phase all the controls still appear to work.

**Comment by Noltari** [comment]
@sparks1372 the best I can do is https://github.com/Noltari/aioairzone-cloud/compare/0.6.2...0.6.3
With these changes, it should work with an advanced user (I've tested it), but the following data won't be available as it requires admin permissions:
- https://developers.airzonecloud.com/docs/web-api/#get-/devices/-deviceId-/config
- https://developers.airzonecloud.com/docs/web-api/#get-/devices/ws/-wsId-/status

Also, forget about basic users since that won't be possible as per API design incompatibilities.
TBH, for me this is just paranoia since I really don't see the issue on using an admin user for this.
